name: NSE Automation
on:
  workflow_dispatch:
  # schedule:
  # - cron: '0 18 * * *'

jobs:
  build:
    runs-on: windows-latest
    
    if: github.ref == 'refs/heads/NSE_Sprint21_22_Yunus'
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    # - name: Install Google Chrome 
    #   run: choco install googlechrome --no-progress -y --ignore-checksums
    - name: Download Google Chrome installer
      run: |
        Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/latest/chrome_installer.exe" -OutFile "$env:TEMP\chrome_installer.exe"
    - name: Install Google Chrome
      run: |
        Start-Process -FilePath "$env:TEMP\chrome_installer.exe" -ArgumentList "/silent", "/install" -Wait
       
    - name: Build with Maven
      run: mvn -B clean install test -PNSE -Denv=UAT -Dsheet=NS_Data.xlsx -DBROWSERSTACK_AUTOMATION=false
    - name: List files for debugging
      if: always()
      run: |
        echo "Listing files in ${{ github.workspace }}/TestReport:"
        Get-ChildItem "${{ github.workspace }}\TestReport\"
    - name: Find latest report
      if: always()
      id: find_report
      run: |
        $latestReport = Get-ChildItem "${{ github.workspace }}\TestReport\" -Filter 'Web_AutomationReport*.html' | Sort-Object LastWriteTime -Descending | Select-Object -First 1
        if ($latestReport) {
          echo "Latest report found: $($latestReport.FullName)"
          echo "latest_report_path=$($latestReport.FullName)" >> $env:GITHUB_ENV
        } else {
          Write-Error "No report found"
        }
    - name: Upload latest report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: latest-report
        path: ${{ env.latest_report_path }}
  # - name: Download latest report
  #   if: always()
  #   uses: actions/download-artifact@v2
  #   with:
  #     name: ${{ steps.find_report.outputs.latest_report_path }}
  #     path: ${{ github.workspace }}\Attachments\
